version: '3'

services:
  rathumakara_api:
    container_name: rathumakara_discord_bot
    build:
      context: ../../
      dockerfile: Deployment/Development/Dockerfile
    environment:
      OAUTH2_CLIENT_ID: ${OAUTH2_CLIENT_ID}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET}
      OAUTH2_REDIRECT_URI: ${OAUTH2_REDIRECT_URI}
      API_BASE_URL: ${API_BASE_URL}
      DISCORD_BOT_REST_API: ${DISCORD_BOT_REST_API}
      BOT_COMMANDER_ROLE_ID: ${BOT_COMMANDER_ROLE_ID}
      WEB_AUTH_KEY: ${WEB_AUTH_KEY}
    ports:
      - "5000:5000"